//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociateAppraisals.Model_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateWork
    {
        public int WorkId { get; set; }
        public int AssociateId { get; set; }
        public string ClientName { get; set; }
        public string ClientMatter { get; set; }
        public string MatterName { get; set; }
        public Nullable<double> Hours { get; set; }
    
        public virtual Associate Associate { get; set; }
    }
}
