//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociateAppraisals.Model_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateAppraisalQuestionAnswer
    {
        public int AssociateAppraisalQuestionAnswerId { get; set; }
        public int AppraisalQuestionId { get; set; }
        public int AssociateAppraisalId { get; set; }
        public string Answer { get; set; }
    
        public virtual AppraisalQuestion AppraisalQuestion { get; set; }
        public virtual AssociateAppraisal AssociateAppraisal { get; set; }
    }
}
