//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociateAppraisals.Model_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssociateAppraisalsEntities : DbContext
    {
        public AssociateAppraisalsEntities()
            : base("name=AssociateAppraisalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appraisal> Appraisals { get; set; }
        public virtual DbSet<AppraisalQuestion> AppraisalQuestions { get; set; }
        public virtual DbSet<AppraisalQuestionGroup> AppraisalQuestionGroups { get; set; }
        public virtual DbSet<AppraisalQuestionType> AppraisalQuestionTypes { get; set; }
        public virtual DbSet<Associate> Associates { get; set; }
        public virtual DbSet<AssociateAppraisal> AssociateAppraisals { get; set; }
        public virtual DbSet<AssociateAppraisalQuestionAnswer> AssociateAppraisalQuestionAnswers { get; set; }
        public virtual DbSet<AssociateWork> AssociateWorks { get; set; }
        public virtual DbSet<CompleteView> CompleteViews { get; set; }
    }
}
