//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociateAppraisals.Model_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompleteView
    {
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public Nullable<int> GradYear { get; set; }
        public string ClientName { get; set; }
        public string ClientMatter { get; set; }
        public Nullable<double> Hours { get; set; }
    }
}
