//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessDevelopmentReport
    {
        public int BusinessDevelopmentReportID { get; set; }
        public int LawyerEmployeeID { get; set; }
        public string PendingActivities { get; set; }
        public string CompletedActivities { get; set; }
        public string NextActivities { get; set; }
        public int ReportMonthNumber { get; set; }
        public int ReportYearNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual LawyerEmployee LawyerEmployee { get; set; }
    }
}
