//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public System.Guid ChangeLogID { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public int EmployeeID { get; set; }
        public string TableChanged { get; set; }
        public string Fieldchanged { get; set; }
        public string RowID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }
}
