//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerTicketInfo
    {
        public int TicketNo { get; set; }
        public System.DateTime CallDate { get; set; }
        public string Description { get; set; }
        public int TakenBy { get; set; }
        public int AssignedTo { get; set; }
        public Nullable<int> Application { get; set; }
        public Nullable<int> System { get; set; }
        public string KeyWords { get; set; }
        public int Status { get; set; }
        public Nullable<int> UserLoginID { get; set; }
        public int ServiceTagID { get; set; }
    }
}
