//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerTicketEvent
    {
        public int TicketEventID { get; set; }
        public int TicketID { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
        public int EnteredBy { get; set; }
    }
}
