//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralInfo
    {
        public int PeripheralsID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> AssetTag { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Warranty { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchaseVendor { get; set; }
        public Nullable<int> AssignedUserID { get; set; }
        public Nullable<int> UsageStatusID { get; set; }
    }
}
