//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerDataImport
    {
        public string Computer { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string Type { get; set; }
        public string Service_Tag { get; set; }
        public string Processor { get; set; }
        public string Clock { get; set; }
        public string Bios { get; set; }
        public string Memory { get; set; }
        public string Hard_disks { get; set; }
        public string Remov_disks { get; set; }
        public string CD_ROM { get; set; }
        public string Video_card { get; set; }
        public string Sound_card { get; set; }
        public string Network_cards { get; set; }
        public string Oper_system { get; set; }
        public string Booted { get; set; }
        public string Uptime { get; set; }
        public string User { get; set; }
        public int ID { get; set; }
    }
}
