//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DavisgramLink
    {
        public int DavisgramLinkID { get; set; }
        public int DavisgramLinkCategoryID { get; set; }
        public string Text { get; set; }
        public string NavigateUrl { get; set; }
        public string CssClass { get; set; }
        public bool OpenInNewWindow { get; set; }
    
        public virtual DavisgramLinkCategory DavisgramLinkCategory { get; set; }
    }
}
