//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGS_EnterpriseEntities : DbContext
    {
        public DGS_EnterpriseEntities()
            : base("name=DGS_EnterpriseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaOfExpertise> AreaOfExpertises { get; set; }
        public virtual DbSet<BusinessDevelopmentReport> BusinessDevelopmentReports { get; set; }
        public virtual DbSet<ComputerInfo> ComputerInfoes { get; set; }
        public virtual DbSet<CorporateRole> CorporateRoles { get; set; }
        public virtual DbSet<CoverageLevel> CoverageLevels { get; set; }
        public virtual DbSet<DavisgramLink> DavisgramLinks { get; set; }
        public virtual DbSet<DavisgramLinkCategory> DavisgramLinkCategories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<ExemptStatu> ExemptStatus { get; set; }
        public virtual DbSet<GradLevel> GradLevels { get; set; }
        public virtual DbSet<GuideBookEmployeeDepartment> GuideBookEmployeeDepartments { get; set; }
        public virtual DbSet<GuideBookPeopleSearchCriteria> GuideBookPeopleSearchCriterias { get; set; }
        public virtual DbSet<HireAndTerminationDate> HireAndTerminationDates { get; set; }
        public virtual DbSet<InterfaceObject> InterfaceObjects { get; set; }
        public virtual DbSet<Key> Keys { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LawyerAreaOfExpertise> LawyerAreaOfExpertises { get; set; }
        public virtual DbSet<LawyerBarNumber> LawyerBarNumbers { get; set; }
        public virtual DbSet<LawyerEmployee> LawyerEmployees { get; set; }
        public virtual DbSet<PhotoGalleryCategory> PhotoGalleryCategories { get; set; }
        public virtual DbSet<PracticeGroup> PracticeGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeOffRequest> TimeOffRequests { get; set; }
        public virtual DbSet<TimeOffRequestCoverage> TimeOffRequestCoverages { get; set; }
        public virtual DbSet<TimeOffRequestHour> TimeOffRequestHours { get; set; }
        public virtual DbSet<TimeOffRequestType> TimeOffRequestTypes { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<ClientlinkPermissionsList> ClientlinkPermissionsLists { get; set; }
        public virtual DbSet<ComputerApplicationList> ComputerApplicationLists { get; set; }
        public virtual DbSet<ComputerDataImport> ComputerDataImports { get; set; }
        public virtual DbSet<ComputerIncomingRequest> ComputerIncomingRequests { get; set; }
        public virtual DbSet<ComputerPeripheralInfo> ComputerPeripheralInfoes { get; set; }
        public virtual DbSet<ComputerPeripheralList> ComputerPeripheralLists { get; set; }
        public virtual DbSet<ComputerStatusList> ComputerStatusLists { get; set; }
        public virtual DbSet<ComputerSystemList> ComputerSystemLists { get; set; }
        public virtual DbSet<ComputerTicketEvent> ComputerTicketEvents { get; set; }
        public virtual DbSet<ComputerTicketInfo> ComputerTicketInfoes { get; set; }
        public virtual DbSet<ComputerUsageStatusList> ComputerUsageStatusLists { get; set; }
        public virtual DbSet<EmployeeLanguage> EmployeeLanguages { get; set; }
        public virtual DbSet<RecruitingApplicant> RecruitingApplicants { get; set; }
        public virtual DbSet<RecruitingApplicantAddress> RecruitingApplicantAddresses { get; set; }
        public virtual DbSet<RecruitingApplicantEmail> RecruitingApplicantEmails { get; set; }
        public virtual DbSet<RecruitingApplicantPhone> RecruitingApplicantPhones { get; set; }
        public virtual DbSet<RecruitingCorrespondence> RecruitingCorrespondences { get; set; }
        public virtual DbSet<RecruitingCorrespondenceType> RecruitingCorrespondenceTypes { get; set; }
        public virtual DbSet<RecruitingEmailType> RecruitingEmailTypes { get; set; }
        public virtual DbSet<RecruitingEvaluationType> RecruitingEvaluationTypes { get; set; }
        public virtual DbSet<RecruitingHeadhunter> RecruitingHeadhunters { get; set; }
        public virtual DbSet<RecruitingHRApplicantEmail> RecruitingHRApplicantEmails { get; set; }
        public virtual DbSet<RecruitingHRApplicantPhone> RecruitingHRApplicantPhones { get; set; }
        public virtual DbSet<RecruitingHRApplication> RecruitingHRApplications { get; set; }
        public virtual DbSet<RecruitingHRFieldOFLaw> RecruitingHRFieldOFLaws { get; set; }
        public virtual DbSet<RecruitingHRHeadHunter> RecruitingHRHeadHunters { get; set; }
        public virtual DbSet<RecruitingHRPosition> RecruitingHRPositions { get; set; }
        public virtual DbSet<RecruitingInterviewForm> RecruitingInterviewForms { get; set; }
        public virtual DbSet<RecruitingInterviewLineItem> RecruitingInterviewLineItems { get; set; }
        public virtual DbSet<RecruitingPhoneType> RecruitingPhoneTypes { get; set; }
        public virtual DbSet<RecruitingPosition> RecruitingPositions { get; set; }
        public virtual DbSet<RecruitingSchoolAttendance> RecruitingSchoolAttendances { get; set; }
        public virtual DbSet<RecruitingSchool> RecruitingSchools { get; set; }
        public virtual DbSet<RecruitingYearInSchool> RecruitingYearInSchools { get; set; }
        public virtual DbSet<Salutation> Salutations { get; set; }
        public virtual DbSet<StateAbbreviation> StateAbbreviations { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
    }
}
