//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideBookPeopleSearchCriteria
    {
        public int GuideBookPeopleSearchCriteriaID { get; set; }
        public string Name { get; set; }
        public string DisplayText { get; set; }
        public string Query { get; set; }
        public bool UserSelectable { get; set; }
        public int Sequence { get; set; }
    }
}
