//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceObject
    {
        public System.Guid InterfaceObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectTitle { get; set; }
    }
}
