//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int KeyID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> IntegroID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
