//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawyerEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LawyerEmployee()
        {
            this.BusinessDevelopmentReports = new HashSet<BusinessDevelopmentReport>();
            this.Educations = new HashSet<Education>();
            this.LawyerAreaOfExpertises = new HashSet<LawyerAreaOfExpertise>();
            this.LawyerBarNumbers = new HashSet<LawyerBarNumber>();
        }
    
        public int LawyerEmployeeID { get; set; }
        public Nullable<int> PracticeGroupID { get; set; }
        public Nullable<int> SecretaryEmployeeID { get; set; }
        public string PracticeHistory { get; set; }
        public string JudicialClerkship { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessDevelopmentReport> BusinessDevelopmentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LawyerAreaOfExpertise> LawyerAreaOfExpertises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LawyerBarNumber> LawyerBarNumbers { get; set; }
        public virtual PracticeGroup PracticeGroup { get; set; }
    }
}
