//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawyerAreaOfExpertise
    {
        public int LawyerEmployeeID { get; set; }
        public int AreaOfExpertiseID { get; set; }
        public string Notes { get; set; }
    
        public virtual AreaOfExpertise AreaOfExpertise { get; set; }
        public virtual LawyerEmployee LawyerEmployee { get; set; }
    }
}
