//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingApplicant
    {
        public int ApplicationID { get; set; }
        public System.DateTime ApplicationReceivedDate { get; set; }
        public Nullable<int> ApplicantSalutationID { get; set; }
        public string ApplicantFirstName { get; set; }
        public string ApplicantMiddleName { get; set; }
        public string ApplicantLastName { get; set; }
        public string ApplicantNamePronounciation { get; set; }
        public string ResumeFileName { get; set; }
        public string WritingSampleFileName { get; set; }
        public Nullable<int> AreaOfExpertiseID { get; set; }
        public Nullable<int> YearInSchool { get; set; }
        public Nullable<System.DateTime> YearInSchoolUpdated { get; set; }
        public Nullable<int> AppliedPositionID { get; set; }
        public Nullable<int> CorrespondenceID { get; set; }
        public string ApplicationNotes { get; set; }
        public Nullable<int> HeadhunterID { get; set; }
        public Nullable<int> PositionDepartmentID { get; set; }
        public Nullable<int> PositionPracticeGroupID { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<bool> Diverse { get; set; }
    }
}
