//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingCorrespondence
    {
        public int CorrespondenceID { get; set; }
        public int ApplicationID { get; set; }
        public int LetterTypeID { get; set; }
        public Nullable<System.DateTime> LetterSentDate { get; set; }
        public string LetterNotes { get; set; }
        public string LetteriManageID { get; set; }
    }
}
