//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingHRHeadHunter
    {
        public int HeadHunterID { get; set; }
        public string HeadHunterName { get; set; }
        public string HeadhunterAddress1 { get; set; }
        public string HeadhunterAddress2 { get; set; }
        public string HeadhunterCity { get; set; }
        public Nullable<int> HeadhunterStateID { get; set; }
        public string HeadHunterZip { get; set; }
        public string HeadHunterContactName { get; set; }
        public string HeadHunterContactEmail { get; set; }
        public string HeadhunterContactPhone1 { get; set; }
        public string HeadhunterContactPhone2 { get; set; }
    }
}
