//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingSchoolAttendance
    {
        public int SchoolAttendedID { get; set; }
        public int ApplicationID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<System.DateTime> GraduateYear { get; set; }
        public string Degree { get; set; }
        public string GradePointAverage { get; set; }
        public string TranscriptFileName { get; set; }
    }
}
