//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingHRApplicantPhone
    {
        public int PhoneID { get; set; }
        public int ApplicationID { get; set; }
        public int PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
    }
}
