//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int SystemSettingID { get; set; }
        public string SystemKey { get; set; }
        public string SystemValue { get; set; }
        public Nullable<byte> Type { get; set; }
    }
}
