//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffRequest
    {
        public int TimeOffRequestID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Notes { get; set; }
        public string NormalStartTime { get; set; }
        public string NormalEndTime { get; set; }
        public bool Approved { get; set; }
        public Nullable<bool> StartHalfDay { get; set; }
        public Nullable<bool> EndHalfDay { get; set; }
        public Nullable<bool> Report { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsAccounted { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
