//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffRequestHour
    {
        public int TimeOffRequestHourID { get; set; }
        public int TimeOffRequestID { get; set; }
        public int TimeOffRequestTypeID { get; set; }
        public decimal Hour { get; set; }
        public string OtherDescription { get; set; }
    
        public virtual TimeOffRequestType TimeOffRequestType { get; set; }
    }
}
