//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGS_Enterprise.ModelDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffRequestCoverage
    {
        public int TimeOffRequestCoverageID { get; set; }
        public int TimeOffRequestID { get; set; }
        public int CoverageEmployeeId { get; set; }
        public int CoverageLevelID { get; set; }
        public Nullable<int> CovererEmployeeid { get; set; }
        public string Notes { get; set; }
        public bool Approved { get; set; }
    
        public virtual CoverageLevel CoverageLevel { get; set; }
    }
}
